#!/bin/bash

tag=Name
value=Web_VPC

aws ec2 describe-vpcs \
  --filters Name=tag:$tag,Values=$value \
  --output text

igwid=
vpcid=
aws ec2 attach-internet-gateway \
  --internet-gateway-id $igwid \
  --vpc-id $vpcid
